import Head from "next/head";
import Image from "next/image";
import styles from "../styles/home.module.css";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { sortByDate } from "../utils/utils";
import BlogCard from "../components/BlogCard";
import { BsInstagram, BsFacebook } from "react-icons/bs";
import Link from "next/link";
import SidePanel from "../components/SidePanel";

export default function Home({ posts }) {
  return (
    <div className="page">
      <Head>
        <title>Anjali Sarma | manor_anubhuti</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <div className="container">
        <section className={styles.blogs}>
          {posts.map((post, index) => {
            return <BlogCard key={index} post={post} />;
          })}
        </section>
        <SidePanel />
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join("posts"));

  const posts = files.map((filename) => {
    const slug = filename.replace(".md", "");

    const markdownWithMeta = fs.readFileSync(
      path.join("posts", filename),
      "utf-8"
    );
    const { data: frontmatter } = matter(markdownWithMeta);

    return {
      slug,
      frontmatter,
    };
  });

  return {
    props: {
      posts: posts.sort(sortByDate),
    },
  };
};
